// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/explore/:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/[name].get').default>>>>
    }
    '/api/explore/:name/roadmap': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/[name]/roadmap.post').default>>>>
    }
    '/api/explore': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/explore/index.get').default>>>>
    }
    '/api/graph': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/graph.get').default>>>>
    }
    '/api/graph/build': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/graph/build.post').default>>>>
    }
    '/api/knowledge': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/knowledge.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/knowledge.post').default>>>>
    }
    '/api/knowledge/from-paper': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/knowledge/from-paper.post').default>>>>
    }
    '/api/knowledge/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/knowledge/search.get').default>>>>
    }
    '/api/papers/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/[id].get').default>>>>
    }
    '/api/papers/:id/close-read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/[id]/close-read.post').default>>>>
    }
    '/api/papers/:id/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/[id]/content.get').default>>>>
    }
    '/api/papers/:id/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/[id]/generate.post').default>>>>
    }
    '/api/papers/:id/status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/[id]/status.post').default>>>>
    }
    '/api/papers/:id/tags': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/[id]/tags.post').default>>>>
    }
    '/api/papers/generate-batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/generate-batch.post').default>>>>
    }
    '/api/papers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/papers/index.get').default>>>>
    }
    '/api/projects': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects.get').default>>>>
    }
    '/api/tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tags.get').default>>>>
    }
    '/api/tasks/:taskId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tasks/[taskId].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}