// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/25/2026, 3:24:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/nie/Claude/papers/scholaraio/scholaraio/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nie/Claude/papers/scholaraio/scholaraio/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nie/Claude/papers/scholaraio/scholaraio/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nie/Claude/papers/scholaraio/scholaraio/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nie/Claude/papers/scholaraio/scholaraio/web/plugins/**/*.{js,ts,mjs}","/home/nie/Claude/papers/scholaraio/scholaraio/web/composables/**/*.{js,ts,mjs}","/home/nie/Claude/papers/scholaraio/scholaraio/web/utils/**/*.{js,ts,mjs}","/home/nie/Claude/papers/scholaraio/scholaraio/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nie/Claude/papers/scholaraio/scholaraio/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/nie/Claude/papers/scholaraio/scholaraio/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/nie/Claude/papers/scholaraio/scholaraio/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;